#!/bin/bash 

# KARAN CHAUDHARY 
# CHECK IF INPUT NUMBER IS +VE, -VE OR ZERO

# FUNCTION TO MATCH THE INPUT BEFORE PERFORMING ARTHMATIC EXPRESSION
is_number() {
    [[ $1 =~ ^-?[0-9]+$ ]]
}

# TAKING INPUT FROM THE USER STORING IN num VARIABLE 

read -p "ENTER YOUR NUMBERE HERE: " num
 
# CHECKING IF THE INPUT IS A NUMBER OR NOT
if is_number "$num"; then

# IF NUMBER RECEIVED AS AN INPUT THEN PROCEED WITH CHECKING NUMBER FOR -VE, +VE OR ZERO
if [ $num -gt 0 ] 
then
	echo "INPUT NUMBER IS POSITIVE NUMBER."
elif [ $num -lt 0 ]
then
	echo "INPUT NUMBER IS NEGATIVE NUMBER."
elif [ $num -eq 0 ]
then
	echo "INPUT NUMBER IS ZERO."
fi

# IF INPUT IS NOT A NUMBER THEN ECHO NOT A NUMBER
else
	echo "INPUT IS NOT A NUMBER."
fi
